# Generated by Django 4.1.6 on 2023-05-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_email_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=5, null=True)),
                ('comment_body', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
