# Generated by Django 4.1.6 on 2023-05-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customercomments_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customercomments'),
        ),
    ]
