# Generated by Django 4.1.6 on 2023-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='store.customercomments'),
        ),
    ]
