# Generated by Django 4.1.6 on 2023-05-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_comment_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
